-- EXERCÍCIOS 01

-- 1. CONTE TODAS AS LINHAS DA TABELA ORDERS E DÊ UM APELIDO PARA A COLUNA RETORNADA

SELECT COUNT(*) AS 'Quantidade de PEDIDOS'
FROM ORDERS

-- 2. SELECIONE TODAS AS LINHAS DA TABELA ORDERS COM O STATUS DIFERENTES de 'delivered' OU QUE NÃO TENHAM PEDIDOS APROVADOS

SELECT *
FROM ORDERS
WHERE ORDER_STATUS !='delivered'
OR ORDER_APPROVED_AT IS NULL

-- 3. SELECIONE APENAS AS LINHAS ÚNICAS DA TABELA ORDERS E APENAS AS COLUNAS CUSTOMER_ID, ORDER_ID E ORDER_APROVED_AT E DÊ APELIDOS AS COLUNAS RETORNADAS.

SELECT  DISTINCT ORDER_ID AS 'ID_PEDIDO'
       ,ORDER_STATUS AS 'STATUS_PEDIDO'
       ,CUSTOMER_ID AS 'ID_DO_CLIENTE'
FROM ORDERS;

-- 4. SELECIONE TODOS OS CLIENTES CUJA A CIDADE NÃO INICIA COM O NOME 'franca'

SELECT * 
FROM CUSTOMERS
WHERE CUSTOMER_CITY NOT LIKE 'franca%'

-- 5. SELECIONE AS LINHAS ÚNICAS DA TABELA ORDERS E APRESENTE APENAS OS DADOS DA COLUNA ORDER_STATUS

SELECT DISTINCT ORDER_STATUS
FROM ORDERS