-- EXERCICIOS 02

-- 1. CONTA A QUANTIDADE DE PEDIDOS E AGRUPE POR CIDADE (UTILIZE AS TABELAS ORDERS E CUSTOMERS)


-- 2. SELECTIONE O ID DO PEDIDO, O STATUS, O ID DO CLIENTE, A CIDADE DO CLIENTE E O ESTADO MESMO QUE ESTE NÃO ESTEJA PRESENTE NA TABELA CUSTOMER


-- 3. SELECIONE O ID DO PEDIDO, A QUANTIDADE DE FOTOS, O PREÇO, O TIPO DE PAGAMENTO E O VALOR DE PAGAMENTO DOS PRODUTOS QUE TEM MAIS DE 3 FOTOS
-- (UTILIZE AS TABELAS: PEDIDOS, PAGAMENTOS E ITENS)