-- EXERCÍCIOS 01

-- 1. CONTE TODAS AS LINHAS DA TABELA ORDERS E DÊ UM APELIDO PARA A COLUNA RETORNADA


-- 2. SELECIONE TODAS AS LINHAS DA TABELA ORDERS COM O STATUS DIFERENTES de 'delivered' OU QUE NÃO TENHAM PEDIDOS APROVADOS


-- 3. SELECIONE APENAS AS LINHAS ÚNICAS DA TABELA ORDERS E APENAS AS COLUNAS CUSTOMER_ID, ORDER_ID E ORDER_APROVED_AT E DÊ APELIDOS AS COLUNAS RETORNADAS.


-- 4. SELECIONE TODOS OS CLIENTES CUJA A CIDADE NÃO INICIA COM O NOME 'franca'


-- 5. SELECIONE AS LINHAS ÚNICAS DA TABELA ORDERS E APRESENTE APENAS OS DADOS DA COLUNA ORDER_STATUS