--  SELECIONA TODOS OS REGISTROS DA TABELA ORDERS

SELECT *
FROM ORDERS;


-- SELECIONA TODOS OS REGISTROS DA TABELA ORDERS EXIBINDO APENAS AS COLUNAS ORDER_ID E ORDER_STATUS

SELECT  ORDER_ID
       ,ORDER_STATUS
FROM ORDERS;

-- SELECIONA TODOS OS REGISTROS DA TABELA ORDERS EXIBINDO APENAS AS COLUNAS ORDER_ID, ORDER_STATUS E CUSTOMER_ID

SELECT  ORDER_ID
       ,ORDER_STATUS
       ,CUSTOMER_ID
FROM ORDERS;

-- TRABALHANDO COM ALIAS

SELECT  ORDER_ID AS 'ID_PEDIDO'
       ,ORDER_STATUS AS 'STATUS_PEDIDO'
       ,CUSTOMER_ID AS 'ID_DO_CLIENTE'
FROM ORDERS;


-- SELECIONANDO APENAS LINHAS ÚNICAS

SELECT  DISTINCT ORDER_ID AS 'ID_PEDIDO'
       ,ORDER_STATUS AS 'STATUS_PEDIDO'
       ,CUSTOMER_ID AS 'ID_DO_CLIENTE'
FROM ORDERS;


-- CONTANDO A QUANTIDADE DE REGISTROS RETORNADOS PELA CONSULTA

SELECT COUNT(*)
FROM ORDERS;

-- DANDO UM APELIDO AO RESULTADO RETORNADO

SELECT COUNT(*) AS 'Quantidade de linhas'
FROM ORDERS;


-- CONTANDO A QUANTIDADE DE LINHAS NÃO NULAS DA COLUNA CUSTOMER_ID E DANDO UM APELIDO AO RESULTADO RETORNADO

SELECT COUNT(CUSTOMER_ID) AS 'Quantidade de clientes'
FROM ORDERS;

-- TRABALHANDO COM A OPÇÃO WHERE

SELECT *
FROM ORDERS
WHERE ORDER_STATUS='delivered'


-- CONTANDO TODOS OS REGISTROS COM O STATUS 'delivered'

SELECT COUNT(*)
FROM ORDERS
WHERE ORDER_STATUS='delivered'


-- CONTANDO TODOS OS REGISTROS COM O STATUS DIFERENTE DE 'delivered'

SELECT COUNT(*)
FROM ORDERS
WHERE ORDER_STATUS != 'delivered'

-- SELECIONA TODAS AS LINHAS DA TABELA ORDERS COM O STATUS diferentes de 'delivered' e que não tenha pedidos aprovados

SELECT *
FROM ORDERS
WHERE ORDER_STATUS != 'delivered'
AND ORDER_APPROVED_AT IS NULL

-- SELECIONA TODAS AS LINHAS DA TABELA ORDERS COM O STATUS DIFERENTES de 'delivered' OU QUE NÃO TENHAM PEDIDOS APROVADOS
SELECT *
FROM ORDERS
WHERE ORDER_STATUS !='delivered'
OR ORDER_APPROVED_AT IS NULL

-- CONSULTA TODOS OS CLIENTES CUJA A CIDADE COMEÇA COM MOGI
SELECT * 
FROM CUSTOMERS
WHERE CUSTOMER_CITY LIKE 'mogi%'

-- CONSULTA TODOS OS CLIENTES CUJA A CIDADE NÃO COMEÇA COM MOGI
SELECT * 
FROM CUSTOMERS
WHERE CUSTOMER_CITY NOT LIKE 'mogi%'

-- CONTA A QUANTIDADE DE LINHAS AGRUPANDO OS RESULTADOS PELO ID DO CLIENTE
SELECT COUNT(*)
FROM ORDERS
GROUP BY CUSTOMER_ID

SELECT * FROM ORDER_PAYMENTS

-- SOMA A QUANTIDADE DE VALOR GASTO POR TIPO DE PAGAMENTO.

ELECT PAYMENT_TYPE
      ,SUM(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE

-- CALCULA O VALOR MÉDIO GASTO POR TIPO TE PAGAMENTO

SELECT PAYMENT_TYPE
      ,AVG(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE


-- CALCULA O VALOR MÍNIMO GASTO POR TIPO DE PAGAMENTO

SELECT PAYMENT_TYPE
      ,MIN(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE

-- CALCULA O VALOR MÁXIMO GASTO POR TIPO DE PAGAMENTO

SELECT PAYMENT_TYPE
      ,MAX(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE

-- USANDO A CLAUSULA HAVING

SELECT PAYMENT_TYPE
      ,SUM(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE
HAVING PAYMENT_TYPE IS NOT NULL

-- FILTRANDO O RESULTADO COM A CLÁUSULA WHERE

SELECT PAYMENT_TYPE
      ,SUM(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE
WHERE SUM(PAYMENT_VALUE) > 0

-- USANDO A CLÁUSULA HAVING PARA FILTRAR APENAS GRUPOS COM VALORES MAIOR QUE 0

SELECT PAYMENT_TYPE
      ,SUM(PAYMENT_VALUE)
FROM ORDER_PAYMENTS
GROUP BY PAYMENT_TYPE
HAVING SUM(PAYMENT_VALUE) > 0


--  USANDO A CLÁUSULA ORDER BY PARA ORDENAÇÃO POR ORDEM ALFABÉTICA

SELECT CUSTOMER_ID
      ,CUSTOMER_CITY
      ,CUSTOMER_STATE
FROM CUSTOMERS
ORDER BY CUSTOMER_CITY

--  USANDO A CLÁUSULA ORDER BY PARA ORDENAÇÃO POR ORDEM DESCRECENTE

SELECT CUSTOMER_ID
      ,CUSTOMER_CITY
      ,CUSTOMER_STATE
FROM CUSTOMERS
ORDER BY CUSTOMER_CITY DESC

-- COMBINANDO AS CLÁUSULAS GROUP BY E ORDER BY

SELECT CUSTOMER_STATE
      ,COUNT(*) as 'Quantidade'
FROM CUSTOMERS
GROUP BY CUSTOMER_STATE
ORDER BY 2 DESC;

SELECT * FROM  CUSTOMERS;


-- TRABALHANDO COM JUNÇÕES - ENTENDENDO INNER JOINS

-- SELECIONA OS PEDIDOS, STATUS, O ID DO CLIENTE, A CIDADE E O ESTADO A PARTIR DAS TABELAS ORDERS E CUSTOMERS.

SELECT ORDER_ID
      ,PEDIDO.ORDER_STATUS
      ,CLIENTE.CUSTOMER_ID
      ,CLIENTE.CUSTOMER_CITY
      ,CLIENTE.CUSTOMER_STATE
FROM ORDERS PEDIDO INNER JOIN CUSTOMERS CLIENTE
ON PEDIDO.CUSTOMER_ID = CLIENTE.CUSTOMER_ID


-- LEFT JOIN

-- SELECIONA OS PEDIDOS SE HOUVER PEDIDOS NA TABELA PEDIDOS MAS NÃO NECESSÁRIAMENTE NA TABELA CLIENTES.

SELECT ORDER_ID
      ,PEDIDO.ORDER_STATUS
      ,CLIENTE.CUSTOMER_ID
      ,CLIENTE.CUSTOMER_CITY
      ,CLIENTE.CUSTOMER_STATE
FROM ORDERS PEDIDO LEFT JOIN CUSTOMERS CLIENTE
ON PEDIDO.CUSTOMER_ID = CLIENTE.CUSTOMER_ID


-- RIGHT JOIN

-- SELECIONA OS PEDIDOS SE HOUVER REGISTROS NA TABELA CLIENTES MAS NÃO NECESSÁRIAMENTE NA TABELA PEDIDOS.

SELECT ORDER_ID
      ,PEDIDO.ORDER_STATUS
      ,CLIENTE.CUSTOMER_ID
      ,CLIENTE.CUSTOMER_CITY
      ,CLIENTE.CUSTOMER_STATE
FROM ORDERS PEDIDO RIGHT JOIN CUSTOMERS CLIENTE
ON PEDIDO.CUSTOMER_ID = CLIENTE.CUSTOMER_ID

